"""Alternating offline training for a latent encoder and Flow-Matching decoder.

The training loop is:

1. Freeze the encoder and fit ``g_phi(s, z)`` to replay-buffer actions with
   conditional flow matching and fresh ``z ~ N(0, I)``.
2. Freeze the decoder, invert buffer actions through its deterministic ODE to
   obtain latent behavior targets, then train:
     * Q(s, a) and V(s) with Implicit Q-Learning (IQL), and
     * pi_theta(z | s) with IQL advantage-weighted behavior cloning.

The IQL update order and losses follow the official implementation:
https://github.com/ikostrikov/implicit_q_learning

``data_path`` may point to a D4RL ``.hdf5`` dataset, an ExORL buffer directory
(or one of its parents) containing ``episode_*.npz`` files, or to a pickle:
  states/observations, actions, rewards,
  next_states/next_observations, dones/terminals or masks.

For legacy GoRL buffers without next states, ``--infer_transitions`` derives
next states by shifting within fixed-length episodes.
"""

from __future__ import annotations

import datetime
import ast
import json
import pickle
import sys
import urllib.request
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import jax
import jax_dataclasses as jdc
import numpy as np
import optax
import tyro
from jax import Array
from jax import numpy as jnp
from tqdm import trange

sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))

from flow_policy import networks
from flow_policy.decoder_fm import DecoderFMConfig, DecoderFMState


PyTree = Any


@dataclass
class OfflineConfig:
    """Configuration for alternating offline FM + IQL training."""

    data_path: str | None = None
    d4rl_dataset: str | None = None
    dataset_dir: str = "datasets/d4rl"
    output_dir: str = "results/offline_fm"
    seed: int = 0

    # Alternating optimization.
    num_rounds: int = 5
    decoder_epochs_per_round: int = 10
    iql_steps_per_round: int = 100_000
    batch_size: int = 256
    decoder_batch_size: int = 1024
    max_samples: int | None = None

    # Legacy buffers may only contain (s, a, r).
    infer_transitions: bool = False
    episode_length: int = 1000

    # FM decoder.
    decoder_checkpoint: str | None = None
    decoder_learning_rate: float = 3e-4
    decoder_hidden_size: int = 64
    decoder_num_layers: int = 4
    flow_steps: int = 10
    latent_inverse_steps: int = 10
    n_fm_samples_per_action: int = 8

    # Official-IQL-style hyperparameters.
    discount: float = 0.99
    expectile: float = 0.8
    temperature: float = 0.1
    max_adv_weight: float = 100.0
    target_update_rate: float = 0.005
    actor_learning_rate: float = 3e-4
    critic_learning_rate: float = 3e-4
    value_learning_rate: float = 3e-4
    hidden_size: int = 256
    hidden_layers: int = 2
    log_interval: int = 1000


@dataclass
class ReplayBuffer:
    observations: np.ndarray
    actions: np.ndarray
    rewards: np.ndarray
    next_observations: np.ndarray
    masks: np.ndarray

    def __len__(self) -> int:
        return len(self.observations)


def _first(data: dict[str, Any], *keys: str) -> Any | None:
    for key in keys:
        if key in data:
            return data[key]
    return None


_D4RL_INFOS_URL = (
    "https://raw.githubusercontent.com/Farama-Foundation/D4RL/master/"
    "d4rl/infos.py"
)


def _official_d4rl_urls() -> dict[str, str]:
    """Read the dataset catalog from D4RL without importing legacy D4RL/Gym."""
    try:
        with urllib.request.urlopen(_D4RL_INFOS_URL, timeout=30) as response:
            source = response.read().decode("utf-8")
    except Exception as error:
        raise RuntimeError(
            "Could not fetch the official D4RL dataset catalog. Check network "
            f"access to {_D4RL_INFOS_URL}."
        ) from error

    tree = ast.parse(source, filename=_D4RL_INFOS_URL)
    urls: dict[str, str] | None = None
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if any(isinstance(target, ast.Name) and target.id == "DATASET_URLS"
               for target in node.targets):
            value = ast.literal_eval(node.value)
            if not isinstance(value, dict):
                raise RuntimeError("D4RL DATASET_URLS is not a dictionary.")
            urls = {str(key): str(url) for key, url in value.items()}
            break
    if urls is None:
        raise RuntimeError("Could not find DATASET_URLS in the D4RL catalog.")

    # These entries are generated by short loops below DATASET_URLS in the
    # official file, so they are not part of its literal dictionary.
    locomotion = ("halfcheetah", "hopper", "walker2d", "ant")
    qualities = (
        "random", "medium", "expert", "medium-replay", "full-replay",
        "medium-expert",
    )
    for environment in locomotion:
        for quality in qualities:
            quality_file = quality.replace("-", "_")
            for version in (1, 2):
                dataset_id = f"{environment}-{quality}-v{version}"
                filename = f"{environment}_{quality_file}-v{version}.hdf5"
                urls[dataset_id] = (
                    "http://rail.eecs.berkeley.edu/datasets/offline_rl/"
                    f"gym_mujoco_v{version}/{filename}"
                )
    for environment in ("hammer", "pen", "relocate", "door"):
        for quality in ("human", "expert", "cloned"):
            dataset_id = f"{environment}-{quality}-v1"
            urls[dataset_id] = (
                "http://rail.eecs.berkeley.edu/datasets/offline_rl/"
                f"hand_dapg_v1/{dataset_id}.hdf5"
            )
    return urls


def _download_d4rl_dataset(dataset_id: str, dataset_dir: Path) -> Path:
    """Download one official D4RL dataset into this project's dataset tree."""
    if not dataset_id or Path(dataset_id).name != dataset_id:
        raise ValueError("d4rl_dataset must be a D4RL task ID, not a path.")
    dataset_dir.mkdir(parents=True, exist_ok=True)
    destination = dataset_dir / f"{dataset_id}.hdf5"
    if destination.is_file() and destination.stat().st_size > 0:
        print(f"Using cached D4RL dataset: {destination}")
        return destination

    urls = _official_d4rl_urls()
    if dataset_id not in urls:
        examples = ", ".join(sorted(urls)[:8])
        raise ValueError(
            f"Unknown D4RL dataset {dataset_id!r}. Official catalog contains "
            f"{len(urls)} tasks, for example: {examples}."
        )
    url = urls[dataset_id].replace("http://", "https://", 1)
    temporary = destination.with_suffix(destination.suffix + ".part")
    print(f"Downloading {dataset_id} from {url}")

    def report(blocks: int, block_size: int, total_size: int) -> None:
        downloaded = blocks * block_size
        if total_size > 0:
            percent = min(100.0, downloaded * 100.0 / total_size)
            print(
                f"\r  {min(downloaded, total_size) / 2**20:.1f}/"
                f"{total_size / 2**20:.1f} MiB ({percent:.1f}%)",
                end="",
                flush=True,
            )

    try:
        urllib.request.urlretrieve(url, temporary, reporthook=report)
        print()
        if temporary.stat().st_size == 0:
            raise RuntimeError("downloaded file is empty")
        temporary.replace(destination)
    except Exception as error:
        if temporary.exists():
            temporary.unlink()
        raise RuntimeError(f"Failed to download {dataset_id} from {url}.") from error
    print(f"Saved D4RL dataset to {destination}")
    return destination


def _resolve_data_path(config: OfflineConfig) -> Path:
    if config.data_path is not None and config.d4rl_dataset is not None:
        raise ValueError("Use either --data-path or --d4rl-dataset, not both.")
    if config.d4rl_dataset is not None:
        project_dir = Path(__file__).resolve().parent
        dataset_dir = Path(config.dataset_dir).expanduser()
        if not dataset_dir.is_absolute():
            dataset_dir = project_dir / dataset_dir
        return _download_d4rl_dataset(config.d4rl_dataset, dataset_dir)
    if config.data_path is None:
        raise ValueError("Provide --data-path or --d4rl-dataset.")
    return Path(config.data_path).expanduser()


def _load_exorl_directory(path: Path) -> dict[str, np.ndarray]:
    """Load the episode layout produced by denisyarats/exorl/download.sh."""
    episode_files = sorted(path.glob("episode_*.npz"))
    if not episode_files:
        candidates = sorted(path.glob("**/episode_*.npz"))
        buffer_dirs = {candidate.parent for candidate in candidates}
        if len(buffer_dirs) != 1:
            found = ", ".join(str(item) for item in sorted(buffer_dirs))
            raise ValueError(
                f"{path} must contain exactly one ExORL buffer; found "
                f"{len(buffer_dirs)} ({found or 'none'}). Point --data-path "
                "at a specific .../buffer directory."
            )
        episode_files = candidates

    observations: list[np.ndarray] = []
    actions: list[np.ndarray] = []
    rewards: list[np.ndarray] = []
    next_observations: list[np.ndarray] = []
    masks: list[np.ndarray] = []
    for episode_path in episode_files:
        with np.load(episode_path) as episode:
            required = {"observation", "action", "reward", "discount"}
            missing = required.difference(episode.files)
            if missing:
                raise KeyError(f"{episode_path} is missing fields: {sorted(missing)}")

            # ExORL stores the reset time-step at index 0. Its action/reward/
            # discount are placeholders; transition t uses fields at t + 1.
            obs = np.asarray(episode["observation"], dtype=np.float32)
            action = np.asarray(episode["action"], dtype=np.float32)
            reward = np.asarray(episode["reward"], dtype=np.float32).reshape(-1)
            discount = np.asarray(episode["discount"], dtype=np.float32).reshape(-1)
            if not (len(obs) == len(action) == len(reward) == len(discount)):
                raise ValueError(f"Inconsistent episode lengths in {episode_path}.")
            if len(obs) < 2:
                continue
            observations.append(obs[:-1])
            actions.append(action[1:])
            rewards.append(reward[1:])
            next_observations.append(obs[1:])
            masks.append(discount[1:])

    if not observations:
        raise ValueError(f"No non-empty ExORL episodes found under {path}.")
    return {
        "observations": np.concatenate(observations),
        "actions": np.concatenate(actions),
        "rewards": np.concatenate(rewards),
        "next_observations": np.concatenate(next_observations),
        "masks": np.concatenate(masks),
    }


def _load_d4rl_hdf5(path: Path) -> dict[str, np.ndarray]:
    """Load a raw D4RL HDF5 file using qlearning_dataset semantics.

    Raw D4RL locomotion files do not contain next observations. They are
    obtained by shifting observations by one row. Transitions at a time-limit
    boundary are dropped so that the next observation never comes from the
    reset of the following episode, matching d4rl.qlearning_dataset's default
    ``terminate_on_end=False`` behavior.
    """
    try:
        import h5py
    except ImportError as error:
        raise ImportError(
            "Loading a D4RL .hdf5 file requires h5py. Install the project "
            "requirements or run `pip install h5py`."
        ) from error

    data: dict[str, np.ndarray] = {}
    with h5py.File(path, "r") as file:
        def collect(name: str, item: Any) -> None:
            if isinstance(item, h5py.Dataset):
                data[name] = item[()]

        file.visititems(collect)

    required = {"observations", "actions", "rewards", "terminals"}
    missing = required.difference(data)
    if missing:
        raise KeyError(f"{path} is missing D4RL fields: {sorted(missing)}")

    observations = np.asarray(data["observations"], dtype=np.float32)
    actions = np.asarray(data["actions"], dtype=np.float32)
    rewards = np.asarray(data["rewards"], dtype=np.float32).reshape(-1)
    terminals = np.asarray(data["terminals"], dtype=bool).reshape(-1)
    if not (len(observations) == len(actions) == len(rewards) == len(terminals)):
        raise ValueError(f"Inconsistent D4RL array lengths in {path}.")
    if len(observations) < 2:
        raise ValueError(f"D4RL dataset {path} has fewer than two rows.")

    timeouts = data.get("timeouts")
    if timeouts is None:
        # v2 Gym locomotion trajectories have a 1000-step horizon. This is
        # the fallback used by D4RL when explicit timeout metadata is absent.
        timeouts = np.zeros(len(observations), dtype=bool)
        episode_step = 0
        for index in range(len(observations)):
            final_timestep = episode_step == 999
            timeouts[index] = final_timestep
            if terminals[index] or final_timestep:
                episode_step = 0
            else:
                episode_step += 1
    else:
        timeouts = np.asarray(timeouts, dtype=bool).reshape(-1)
        if len(timeouts) != len(observations):
            raise ValueError(f"D4RL timeouts length does not match {path}.")

    # Row i uses observation[i + 1] as its successor. The last row has no
    # stored successor, and timeout rows are excluded to avoid reset leakage.
    keep = ~timeouts[:-1]
    return {
        "observations": observations[:-1][keep],
        "actions": actions[:-1][keep],
        "rewards": rewards[:-1][keep],
        "next_observations": observations[1:][keep],
        "terminals": terminals[:-1][keep].astype(np.float32),
    }


def load_replay_buffer(config: OfflineConfig) -> ReplayBuffer:
    """Load D4RL HDF5, ExORL directories, or common offline-RL pickles."""
    data_path = _resolve_data_path(config)
    if data_path.is_dir():
        data = _load_exorl_directory(data_path)
    elif data_path.suffix.lower() in {".h5", ".hdf5"}:
        data = _load_d4rl_hdf5(data_path)
    else:
        with open(data_path, "rb") as file:
            data = pickle.load(file)
    if not isinstance(data, dict):
        raise TypeError("The offline dataset must be a pickled dictionary.")

    observations = _first(data, "observations", "states", "obs")
    actions = _first(data, "actions", "action")
    rewards = _first(data, "rewards", "reward")
    next_observations = _first(
        data, "next_observations", "next_states", "next_obs"
    )
    masks = _first(data, "masks", "discounts")
    terminals = _first(data, "terminals", "dones", "done")
    timeouts = _first(data, "timeouts", "truncations", "truncated")

    if observations is None or actions is None or rewards is None:
        raise KeyError(
            "Dataset needs observations/states, actions, and rewards."
        )

    observations = np.asarray(observations, dtype=np.float32)
    actions = np.asarray(actions, dtype=np.float32)
    rewards = np.asarray(rewards, dtype=np.float32).reshape(-1)

    if next_observations is None:
        if not config.infer_transitions:
            raise KeyError(
                "Dataset has no next_observations/next_states. Use "
                "--infer_transitions only if rows are ordered in fixed-length "
                "episodes, or regenerate the buffer with next states."
            )
        if config.episode_length < 2:
            raise ValueError("episode_length must be >= 2.")
        usable = (len(observations) // config.episode_length) * config.episode_length
        if usable == 0:
            raise ValueError("Not enough rows for one inferred episode.")
        observations = observations[:usable]
        actions = actions[:usable]
        rewards = rewards[:usable]
        next_observations = np.roll(observations, -1, axis=0)
        inferred_terminal = np.zeros(usable, dtype=np.float32)
        inferred_terminal[config.episode_length - 1 :: config.episode_length] = 1.0
        # Avoid crossing episode boundaries. The value is masked on these rows.
        next_observations[inferred_terminal.astype(bool)] = observations[
            inferred_terminal.astype(bool)
        ]
        terminals = inferred_terminal
    else:
        next_observations = np.asarray(next_observations, dtype=np.float32)

    n = len(observations)
    if not all(len(x) == n for x in (actions, rewards, next_observations)):
        raise ValueError("All transition arrays must have the same first dimension.")

    if masks is not None:
        masks = np.asarray(masks, dtype=np.float32).reshape(-1)
    elif terminals is not None:
        terminals = np.asarray(terminals, dtype=np.float32).reshape(-1)
        # Match official IQL/D4RL behavior: time-limit truncations bootstrap.
        if timeouts is not None:
            timeouts = np.asarray(timeouts, dtype=np.float32).reshape(-1)
            terminals = terminals * (1.0 - timeouts)
        masks = 1.0 - terminals
    else:
        masks = np.ones(n, dtype=np.float32)

    if len(masks) != n:
        raise ValueError("masks/terminals must match the number of transitions.")

    if config.max_samples is not None and n > config.max_samples:
        rng = np.random.default_rng(config.seed)
        indices = rng.choice(n, config.max_samples, replace=False)
        observations = observations[indices]
        actions = actions[indices]
        rewards = rewards[indices]
        next_observations = next_observations[indices]
        masks = masks[indices]

    return ReplayBuffer(
        observations=observations,
        actions=actions,
        rewards=rewards,
        next_observations=next_observations,
        masks=masks,
    )


def init_decoder(
    config: OfflineConfig, obs_dim: int, action_dim: int, key: Array
) -> DecoderFMState:
    """Create a decoder or restore one supplied by the caller."""
    if config.decoder_checkpoint is not None:
        with open(config.decoder_checkpoint, "rb") as file:
            checkpoint = pickle.load(file)
        state = DecoderFMState.init(
            key,
            checkpoint["obs_dim"],
            checkpoint["action_dim"],
            checkpoint["config"],
        )
        with jdc.copy_and_mutate(state) as state:
            state.params = checkpoint["params"]
            state.obs_stats = checkpoint["obs_stats"]
        if checkpoint["obs_dim"] != obs_dim or checkpoint["action_dim"] != action_dim:
            raise ValueError("Decoder checkpoint dimensions do not match the dataset.")
        return state

    fm_config = DecoderFMConfig(
        flow_steps=config.flow_steps,
        timestep_embed_dim=8,
        hidden_dims=(config.decoder_hidden_size,) * config.decoder_num_layers,
        policy_output_scale=1.0,
        learning_rate=config.decoder_learning_rate,
        batch_size=config.decoder_batch_size,
        num_epochs=config.decoder_epochs_per_round,
        n_samples_per_action=config.n_fm_samples_per_action,
        normalize_observations=True,
        sde_sigma=0.0,
        feather_std=0.0,
    )
    return DecoderFMState.init(key, obs_dim, action_dim, fm_config)


def inverse_fm_batch(
    decoder: DecoderFMState,
    observations: Array,
    actions: Array,
    num_steps: int,
) -> Array:
    """Invert deterministic FM: integrate a(t=0) back to z(t=1).

    DecoderFMState uses the repository's reverse-time convention: generation
    starts at t=1 with z and integrates to t=0. Inversion therefore integrates
    the same learned vector field from t=0 to t=1.
    """
    obs_norm = (observations - decoder.obs_stats.mean) / (
        decoder.obs_stats.std + 1e-8
    )
    times = jnp.linspace(0.0, 1.0, num_steps + 1)

    def step(x_t: Array, pair: tuple[Array, Array]) -> tuple[Array, None]:
        t_current, t_next = pair
        t = jnp.full((*x_t.shape[:-1], 1), t_current)
        velocity = decoder.flow_forward(
            obs_norm, x_t, decoder.embed_timestep(t)
        )
        return x_t + (t_next - t_current) * velocity, None

    z, _ = jax.lax.scan(step, actions, (times[:-1], times[1:]))
    return z


def build_latent_targets(
    decoder: DecoderFMState,
    buffer: ReplayBuffer,
    batch_size: int,
    inverse_steps: int,
) -> np.ndarray:
    """Invert every dataset action once after a decoder refinement phase."""
    inverse_jit = jax.jit(
        lambda obs, act: inverse_fm_batch(decoder, obs, act, inverse_steps)
    )
    chunks: list[np.ndarray] = []
    for start in trange(0, len(buffer), batch_size, desc="Invert actions", leave=False):
        end = min(start + batch_size, len(buffer))
        chunks.append(
            np.asarray(
                inverse_jit(
                    jnp.asarray(buffer.observations[start:end]),
                    jnp.asarray(buffer.actions[start:end]),
                )
            )
        )
    return np.concatenate(chunks, axis=0)


def gaussian_log_prob(params: PyTree, observations: Array, z: Array) -> Array:
    distribution = networks.gaussian_policy_fwd(params, observations)
    return jnp.sum(distribution.log_prob(z), axis=-1)


def expectile_loss(diff: Array, expectile: float) -> Array:
    """Official IQL asymmetric squared loss."""
    weight = jnp.where(diff > 0, expectile, 1.0 - expectile)
    return weight * jnp.square(diff)


def polyak_update(params: PyTree, target_params: PyTree, tau: float) -> PyTree:
    return jax.tree.map(
        lambda p, target: tau * p + (1.0 - tau) * target,
        params,
        target_params,
    )


def make_iql_update(
    config: OfflineConfig,
    actor_optimizer: optax.GradientTransformation,
    critic_optimizer: optax.GradientTransformation,
    value_optimizer: optax.GradientTransformation,
):
    """Build the official-IQL-style V -> actor -> Q -> target update."""

    @jax.jit
    def update(
        actor_params: PyTree,
        actor_opt_state: PyTree,
        q1_params: PyTree,
        q2_params: PyTree,
        critic_opt_state: PyTree,
        value_params: PyTree,
        value_opt_state: PyTree,
        target_q1_params: PyTree,
        target_q2_params: PyTree,
        obs: Array,
        actions: Array,
        rewards: Array,
        next_obs: Array,
        masks: Array,
        latent_actions: Array,
    ):
        # 1. V update: expectile regression to min(target Q1, target Q2).
        target_q = jnp.minimum(
            networks.q_mlp_fwd(target_q1_params, obs, actions),
            networks.q_mlp_fwd(target_q2_params, obs, actions),
        )

        def value_loss_fn(params):
            value = networks.value_mlp_fwd(params, obs)
            loss = jnp.mean(expectile_loss(target_q - value, config.expectile))
            return loss, (value, target_q - value)

        (value_loss, (value, advantage)), value_grads = jax.value_and_grad(
            value_loss_fn, has_aux=True
        )(value_params)
        value_updates, value_opt_state = value_optimizer.update(
            value_grads, value_opt_state, value_params
        )
        value_params = optax.apply_updates(value_params, value_updates)

        # 2. Actor update: advantage-weighted BC on inverse-mapped dataset z.
        # stop_gradient mirrors the official implementation's fixed weights.
        new_value = networks.value_mlp_fwd(value_params, obs)
        actor_advantage = jax.lax.stop_gradient(target_q - new_value)
        exp_advantage = jnp.minimum(
            jnp.exp(actor_advantage * config.temperature),
            config.max_adv_weight,
        )

        def actor_loss_fn(params):
            log_prob = gaussian_log_prob(params, obs, latent_actions)
            return -jnp.mean(exp_advantage * log_prob)

        actor_loss, actor_grads = jax.value_and_grad(actor_loss_fn)(actor_params)
        actor_updates, actor_opt_state = actor_optimizer.update(
            actor_grads, actor_opt_state, actor_params
        )
        actor_params = optax.apply_updates(actor_params, actor_updates)

        # 3. Double-Q Bellman regression to r + gamma * mask * V(s').
        next_value = jax.lax.stop_gradient(
            networks.value_mlp_fwd(value_params, next_obs)
        )
        bellman_target = rewards + config.discount * masks * next_value

        def critic_loss_fn(params):
            q1, q2 = params
            q1_value = networks.q_mlp_fwd(q1, obs, actions)
            q2_value = networks.q_mlp_fwd(q2, obs, actions)
            loss = jnp.mean(
                jnp.square(q1_value - bellman_target)
                + jnp.square(q2_value - bellman_target)
            )
            return loss, (q1_value, q2_value)

        (critic_loss, (q1_value, q2_value)), critic_grads = jax.value_and_grad(
            critic_loss_fn, has_aux=True
        )((q1_params, q2_params))
        critic_updates, critic_opt_state = critic_optimizer.update(
            critic_grads, critic_opt_state, (q1_params, q2_params)
        )
        q1_params, q2_params = optax.apply_updates(
            (q1_params, q2_params), critic_updates
        )

        # 4. Exponential moving average target critic.
        target_q1_params = polyak_update(
            q1_params, target_q1_params, config.target_update_rate
        )
        target_q2_params = polyak_update(
            q2_params, target_q2_params, config.target_update_rate
        )

        metrics = {
            "value_loss": value_loss,
            "actor_loss": actor_loss,
            "critic_loss": critic_loss,
            "value": jnp.mean(value),
            "q1": jnp.mean(q1_value),
            "q2": jnp.mean(q2_value),
            "advantage": jnp.mean(advantage),
            "adv_weight": jnp.mean(exp_advantage),
        }
        return (
            actor_params,
            actor_opt_state,
            q1_params,
            q2_params,
            critic_opt_state,
            value_params,
            value_opt_state,
            target_q1_params,
            target_q2_params,
            metrics,
        )

    return update


def save_checkpoint(
    path: Path,
    config: OfflineConfig,
    decoder: DecoderFMState,
    actor_params: PyTree,
    q1_params: PyTree,
    q2_params: PyTree,
    value_params: PyTree,
    obs_mean: Array,
    obs_std: Array,
    round_index: int,
) -> None:
    checkpoint = {
        "round": round_index,
        "config": asdict(config),
        "encoder_params": actor_params,
        "q1_params": q1_params,
        "q2_params": q2_params,
        "value_params": value_params,
        "observation_mean": obs_mean,
        "observation_std": obs_std,
        "decoder": {
            "params": decoder.params,
            "obs_stats": decoder.obs_stats,
            "config": decoder.config,
        },
    }
    with open(path, "wb") as file:
        pickle.dump(checkpoint, file)


def main(config: OfflineConfig) -> None:
    if config.num_rounds < 1:
        raise ValueError("num_rounds must be at least 1.")
    if config.decoder_epochs_per_round < 1:
        raise ValueError("decoder_epochs_per_round must be at least 1.")
    if config.iql_steps_per_round < 1:
        raise ValueError("iql_steps_per_round must be at least 1.")
    if config.batch_size < 1 or config.decoder_batch_size < 1:
        raise ValueError("Batch sizes must be positive.")
    if config.latent_inverse_steps < 1:
        raise ValueError("latent_inverse_steps must be at least 1.")

    buffer = load_replay_buffer(config)
    output_dir = Path(config.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    with open(output_dir / "config.json", "w") as file:
        json.dump(asdict(config), file, indent=2)

    obs_dim = buffer.observations.shape[-1]
    action_dim = buffer.actions.shape[-1]
    latent_dim = action_dim
    rng_np = np.random.default_rng(config.seed)
    key = jax.random.key(config.seed)
    key, decoder_key, actor_key, q1_key, q2_key, value_key = jax.random.split(
        key, 6
    )

    # IQL networks use normalized observations; Q actions stay in buffer space.
    obs_mean = jnp.asarray(buffer.observations.mean(axis=0))
    obs_std = jnp.asarray(buffer.observations.std(axis=0) + 1e-6)
    normalized_observations = (
        buffer.observations - np.asarray(obs_mean)
    ) / np.asarray(obs_std)
    normalized_next_observations = (
        buffer.next_observations - np.asarray(obs_mean)
    ) / np.asarray(obs_std)

    decoder = init_decoder(config, obs_dim, action_dim, decoder_key)
    # Establish normalization from this buffer. Reset first when a checkpoint
    # was loaded, rather than accidentally double-counting old statistics.
    with jdc.copy_and_mutate(decoder) as decoder:
        decoder.obs_stats = decoder.obs_stats.init((obs_dim,)).update(
            jnp.asarray(buffer.observations)
        )

    hidden_dims = (config.hidden_size,) * config.hidden_layers
    actor_params = networks.mlp_init(
        actor_key, (obs_dim, *hidden_dims, latent_dim * 2)
    )
    q1_params = networks.mlp_init(
        q1_key, (obs_dim + action_dim, *hidden_dims, 1)
    )
    q2_params = networks.mlp_init(
        q2_key, (obs_dim + action_dim, *hidden_dims, 1)
    )
    value_params = networks.mlp_init(
        value_key, (obs_dim, *hidden_dims, 1)
    )
    target_q1_params = jax.tree.map(jnp.copy, q1_params)
    target_q2_params = jax.tree.map(jnp.copy, q2_params)

    actor_optimizer = optax.adam(config.actor_learning_rate)
    critic_optimizer = optax.adam(config.critic_learning_rate)
    value_optimizer = optax.adam(config.value_learning_rate)
    actor_opt_state = actor_optimizer.init(actor_params)
    critic_opt_state = critic_optimizer.init((q1_params, q2_params))
    value_opt_state = value_optimizer.init(value_params)
    iql_update = make_iql_update(
        config, actor_optimizer, critic_optimizer, value_optimizer
    )

    metrics_path = output_dir / "metrics.jsonl"
    started = datetime.datetime.now().isoformat()
    print(
        f"Loaded {len(buffer):,} transitions; obs={obs_dim}, "
        f"action/latent={action_dim}. Started {started}."
    )

    for round_index in range(config.num_rounds):
        print(f"\nRound {round_index + 1}/{config.num_rounds}: decoder BC")

        # Phase A: encoder is untouched; update only the FM decoder.
        batches_per_epoch = max(1, len(buffer) // config.decoder_batch_size)
        decoder_losses: list[float] = []
        for _ in trange(
            config.decoder_epochs_per_round,
            desc="Decoder epochs",
            leave=False,
        ):
            permutation = rng_np.permutation(len(buffer))
            for batch_index in range(batches_per_epoch):
                start = batch_index * config.decoder_batch_size
                indices = permutation[start : start + config.decoder_batch_size]
                if len(indices) == 0:
                    continue
                decoder, decoder_metrics = decoder.train_step(
                    jnp.asarray(buffer.observations[indices]),
                    jnp.asarray(buffer.actions[indices]),
                )
                decoder_losses.append(float(decoder_metrics["loss"]))

        # Frozen decoder supplies behavior latent targets for official IQL AWR.
        latent_targets = build_latent_targets(
            decoder,
            buffer,
            config.decoder_batch_size,
            config.latent_inverse_steps,
        )

        print(f"Round {round_index + 1}/{config.num_rounds}: encoder + IQL")
        latest_metrics: dict[str, Array] = {}
        for step in trange(config.iql_steps_per_round, desc="IQL", leave=False):
            indices = rng_np.integers(0, len(buffer), size=config.batch_size)
            (
                actor_params,
                actor_opt_state,
                q1_params,
                q2_params,
                critic_opt_state,
                value_params,
                value_opt_state,
                target_q1_params,
                target_q2_params,
                latest_metrics,
            ) = iql_update(
                actor_params,
                actor_opt_state,
                q1_params,
                q2_params,
                critic_opt_state,
                value_params,
                value_opt_state,
                target_q1_params,
                target_q2_params,
                jnp.asarray(normalized_observations[indices]),
                jnp.asarray(buffer.actions[indices]),
                jnp.asarray(buffer.rewards[indices]),
                jnp.asarray(normalized_next_observations[indices]),
                jnp.asarray(buffer.masks[indices]),
                jnp.asarray(latent_targets[indices]),
            )
            if (step + 1) % config.log_interval == 0:
                summary = {k: float(v) for k, v in latest_metrics.items()}
                print(f"  step {step + 1}: {summary}")

        record = {
            "round": round_index,
            "decoder_loss": float(np.mean(decoder_losses)),
            **{key: float(value) for key, value in latest_metrics.items()},
        }
        with open(metrics_path, "a") as file:
            file.write(json.dumps(record) + "\n")

        save_checkpoint(
            output_dir / f"checkpoint_round_{round_index:03d}.pkl",
            config,
            decoder,
            actor_params,
            q1_params,
            q2_params,
            value_params,
            obs_mean,
            obs_std,
            round_index,
        )
        print(f"Round summary: {record}")

    save_checkpoint(
        output_dir / "checkpoint_final.pkl",
        config,
        decoder,
        actor_params,
        q1_params,
        q2_params,
        value_params,
        obs_mean,
        obs_std,
        config.num_rounds - 1,
    )
    print(f"Saved final checkpoint to {output_dir / 'checkpoint_final.pkl'}")


if __name__ == "__main__":
    main(tyro.cli(OfflineConfig))
