nohup env XLA_PYTHON_CLIENT_PREALLOCATE=false \
OMP_NUM_THREADS=1 \
MKL_NUM_THREADS=1 \
OPENBLAS_NUM_THREADS=1 \
NUMEXPR_NUM_THREADS=1 \
VECLIB_MAXIMUM_THREADS=1 \
TF_NUM_INTRAOP_THREADS=1 \
TF_NUM_INTEROP_THREADS=1 \
MUJOCO_GL=egl \
PYOPENGL_PLATFORM=egl \
CUDA_VISIBLE_DEVICES=1 \
PYTHONPATH=/root/GoRL:/root/GoRL/envs/robomimic \
python -u scripts/run_gorl_fm.py \
> logs/gorl_origin-$(date +%Y%m%d_%H%M%S).log 2>&1 < /dev/null &
